<Project>
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Deterministic>true</Deterministic>
    <DebugType Condition="'$(Configuration)' == 'Release'">embedded</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">true</DebugSymbols>
    <PathMap Condition="'$(Configuration)' == 'Release'">$(MSBuildThisFileDirectory)=/_/</PathMap>
  </PropertyGroup>
</Project>
